name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
permissions:
  contents: write
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - uses: microsoft/playwright-github-action@v1
    - name: Install dependencies
      run: yarn install
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Tests In Chrome
      run: yarn run tests:allure  
      continue-on-error: true 
          
    - name: Generate Allure report
        if: always()
        uses: afiore/action-allure-report@v0.1.0

    - name: Commit report results
      if: always()
      run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add allure-report -f
          git add allure-results -f
          git add allure-history -f
          git commit -m "[chore] autogenerate Allure report" -a

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public