name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
      with:
        node-version: '14.x'
    - uses: microsoft/playwright-github-action@v1
    - name: Install dependencies
      run: yarn install
    - name: Install Playwright
      run: npx playwright install --with-deps
    - name: Run Tests In Chrome
      run: yarn run tests:allure  
      continue-on-error: true 
        
    - name: Get Allure history
      run: yarn run generate:report
      continue-on-error: true

   - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./public